---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-infra-worker
  namespace: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  name: vault-connection
  namespace: default
spec:
  address: http://vault:8200
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth-temporal-infra-worker
  namespace: default
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: temporal-infra-worker
    serviceAccount: temporal-infra-worker
---
apiVersion: v1
kind: Secret
metadata:
  name: temporal-tls-certs
  namespace: default
type: Opaque
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultPKISecret
metadata:
  namespace: default
  name: vaultpkisecret-temporal-infra-worker
spec:
  vaultAuthRef: vault-auth-temporal-infra-worker
  namespace: default
  mount: pki_int
  role: temporal-infra-worker
  destination:
    name: temporal-tls-certs
  commonName: worker.dahlke.io
  format: pem
  expiryOffset: 5s
  ttl: 60s
  rolloutRestartTargets:
    - kind: Deployment
      name: temporal-infra-worker
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-infra-worker-config
  namespace: default
data:
  TEMPORAL_HOST_URL: "neil-vault-cert-rotation-demo-7ee7106c.sdvdw.tmprl.cloud:7233"
  TEMPORAL_NAMESPACE: "neil-vault-cert-rotation-demo-7ee7106c.sdvdw"
  TEMPORAL_TASK_QUEUE: "provision-infra"
  TF_VAR_prefix: "neil"
  ENCRYPT_PAYLOADS: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: temporal-infra-worker
   namespace: default
   labels:
      app: temporal-infra-worker
spec:
   selector:
      matchLabels:
         app: temporal-infra-worker
   replicas: 1
   template:
      metadata:
         labels:
            app: temporal-infra-worker
      spec:
         serviceAccountName: temporal-infra-worker
         containers:
            - name: temporal-infra-worker
              image: eklhad/temporal-infra-worker:latest
              env:
                - name: TEMPORAL_HOST_URL
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_HOST_URL
                - name: TEMPORAL_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_NAMESPACE
                - name: TEMPORAL_TASK_QUEUE
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TEMPORAL_TASK_QUEUE
                - name: TF_VAR_prefix
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: TF_VAR_prefix
                - name: ENCRYPT_PAYLOADS
                  valueFrom:
                    configMapKeyRef:
                      name: temporal-infra-worker-config
                      key: ENCRYPT_PAYLOADS
                - name: TEMPORAL_MTLS_TLS_CERT
                  value: /vault/secrets/certificate
                - name: TEMPORAL_MTLS_TLS_KEY
                  value: /vault/secrets/private_key
                - name: TEMPORAL_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: temporal-secrets
                      key: cloud-api-key
              resources:
                limits:
                  cpu: "0.5"
                  memory: "512Mi"
                requests:
                  cpu: "0.2"
                  memory: "256Mi"
              volumeMounts:
                - name: tls-certs
                  mountPath: /vault/secrets
                  readOnly: true
         volumes:
            - name: tls-certs
              secret:
                secretName: temporal-tls-certs
                items:
                  - key: certificate
                    path: certificate
                  - key: private_key
                    path: private_key
